# Generated by Django 5.2 on 2025-10-01 00:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_journal_core_journa_date_op_a99831_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entreprise', models.CharField(default=core.models.generate_entreprise_id, help_text="ID unique de 10 caractères pour identifier l'entreprise", max_length=10, unique=True)),
                ('nom', models.CharField(help_text="Nom de l'entreprise", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'entreprise")),
                ('secteur_activite', models.CharField(help_text="Secteur d'activité", max_length=100)),
                ('adresse', models.TextField(help_text='Adresse complète')),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(help_text="Email de contact de l'entreprise", max_length=254)),
                ('site_web', models.URLField(blank=True, help_text="Site web de l'entreprise")),
                ('numero_fiscal', models.CharField(blank=True, help_text='Numéro fiscal', max_length=50)),
                ('nombre_employes', models.IntegerField(default=0, help_text="Nombre d'employés")),
                ('annee_creation', models.IntegerField(help_text='Année de création')),
                ('pack_type', models.CharField(choices=[('basique', 'Basique'), ('professionnel', 'Professionnel'), ('entreprise', 'Entreprise')], default='basique', max_length=20)),
                ('pack_prix', models.FloatField(default=0)),
                ('pack_duree', models.CharField(default='mensuel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='boutique',
            options={'ordering': ['nom'], 'verbose_name': 'Boutique/Entrepôt', 'verbose_name_plural': 'Boutiques/Entrepôts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='boutique',
            name='adresse',
            field=models.TextField(blank=True, help_text="Adresse de l'entrepôt"),
        ),
        migrations.AddField(
            model_name='boutique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nom du responsable', max_length=100),
        ),
        migrations.AddField(
            model_name='boutique',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='boutique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_employee',
            field=models.BooleanField(default=True, help_text="L'employé est-il actif ?"),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, help_text="Poste occupé dans l'entreprise", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.boutique'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.boutique'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.boutique'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.boutique'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='journal',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.entreprise'),
        ),
    ]
