# Generated by Django 5.2 on 2025-10-01 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entreprise_alter_boutique_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email à vérifier', max_length=254)),
                ('verification_code', models.CharField(help_text='Code de vérification à 6 chiffres', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('expired', 'Expiré')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du code")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification Email',
                'verbose_name_plural': 'Vérifications Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
