# Generated by Django 5.2 on 2025-10-02 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_entreprise_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='boutique',
        ),
        migrations.AddField(
            model_name='produit',
            name='code_barres',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='compte_comptable',
            field=models.CharField(blank=True, help_text='Compte comptable lié', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, help_text='Date de péremption', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='devise',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='produit',
            name='dluo',
            field=models.DateField(blank=True, help_text="Date limite d'utilisation optimale", null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='etat_produit',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionné'), ('defectueux', 'Défectueux')], default='neuf', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/images/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='methode_valorisation',
            field=models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('CUMP', 'Coût Unitaire Moyen Pondéré')], default='FIFO', max_length=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='numero_lot',
            field=models.CharField(blank=True, help_text='Numéro de lot/série', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.FloatField(blank=True, help_text='Poids en kg', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='point_commande',
            field=models.IntegerField(default=0, help_text='Point de commande automatique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_gros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de gros', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente unitaire', max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='qr_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='remise_max',
            field=models.FloatField(default=0, help_text='Remise maximale autorisée en %'),
        ),
        migrations.AddField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, help_text='Code produit unique (SKU)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_maximum',
            field=models.IntegerField(default=1000, help_text='Stock maximum recommandé'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_minimum',
            field=models.IntegerField(default=0, help_text="Seuil d'alerte minimum"),
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Liste de mots-clés'),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_tva',
            field=models.FloatField(default=19.25, help_text='Taux de TVA en %'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('carton', 'Carton'), ('paquet', 'Paquet')], default='pièce', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='variante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='volume',
            field=models.FloatField(blank=True, help_text='Volume en m³', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat unitaire", max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='processeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stockage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='systeme_exploitation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Classe CSS pour l'icône", max_length=50)),
                ('couleur', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.entreprise')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='core.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.categorie'),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_fournisseur', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('delai_livraison_jours', models.IntegerField(default=7, help_text='Délai de livraison moyen en jours')),
                ('conditions_paiement', models.CharField(blank=True, max_length=100)),
                ('remise_defaut', models.FloatField(default=0, help_text='Remise par défaut en %')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.fournisseur'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('transfert', 'Transfert'), ('perte', 'Perte'), ('retour', 'Retour')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('quantite_avant', models.IntegerField()),
                ('quantite_apres', models.IntegerField()),
                ('reference_document', models.CharField(blank=True, help_text='Référence du document source', max_length=100)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.boutique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('quantite_reservee', models.IntegerField(default=0, help_text='Quantité réservée pour les commandes')),
                ('emplacement', models.CharField(blank=True, help_text="Emplacement dans l'entrepôt", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.boutique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('produit', 'entrepot')},
            },
        ),
    ]
