# Generated by Django 5.2 on 2025-10-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_produit_options_remove_produit_boutique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='compte_comptable',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_peremption',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='dluo',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='methode_valorisation',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='numero_lot',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='point_commande',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='processeur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='remise_max',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stockage',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='systeme_exploitation',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taux_tva',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='volume',
        ),
        migrations.AddField(
            model_name='produit',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Spécifications techniques (JSON)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(blank=True, help_text='Catégorie (compatibilité)', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_barres',
            field=models.CharField(blank=True, help_text='Code-barres', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Description du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit', null=True, upload_to='produits/images/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, help_text='Marque du produit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modele',
            field=models.CharField(blank=True, help_text='Modèle du produit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(help_text='Nom du produit', max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente (compatibilité)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité totale (calculée)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence produit (compatibilité)', max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('carton', 'Carton'), ('paquet', 'Paquet')], default='piece', max_length=20),
        ),
    ]
