# Generated by Django 5.2 on 2025-10-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_optimize_produit_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commandepartenaire',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='commandeclient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='commandeclient',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='commandeclient',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='commandepartenaire',
            name='partenaire',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='nom',
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commandepartenaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='commandepartenaire',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_partenaire', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Payé', 'Payé'), ('Partiellement payé', 'Partiellement payé'), ('Annulé', 'Annulé')], default='En attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(default='Bafoussam', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.boutique')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.entreprise')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('telephone', 'entreprise')},
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.client'),
        ),
    ]
