# Generated by Django 5.2 on 2025-10-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_commandeclient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('dernier_numero', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_facture', to='core.boutique')),
            ],
            options={
                'ordering': ['boutique', 'annee', 'mois'],
                'unique_together': {('boutique', 'annee', 'mois')},
            },
        ),
    ]
