# Generated by Django 5.2 on 2025-10-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sequencefacture'),
        ('core', '0021_fix_facture_numbers'),
    ]

    operations = [
    ]
