# Generated by Django 5.2 on 2025-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_duplicate_facture_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
