# Generated by Django 5.2 on 2025-10-14 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versement',
            options={'ordering': ['-date_versement'], 'verbose_name': 'Versement', 'verbose_name_plural': 'Versements'},
        ),
        migrations.AddField(
            model_name='versement',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='core.boutique'),
        ),
        migrations.AddField(
            model_name='versement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='core.facture'),
        ),
    ]
