# Generated by Django 5.2 on 2025-10-16 02:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_versement_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('organisation', 'Organisation')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_entreprises', models.IntegerField(default=1)),
                ('max_boutiques', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=2)),
                ('max_produits', models.IntegerField(blank=True, default=50, null=True)),
                ('max_factures_per_month', models.IntegerField(blank=True, default=100, null=True)),
                ('allow_export_csv', models.BooleanField(default=False)),
                ('allow_export_excel', models.BooleanField(default=False)),
                ('allow_import_csv', models.BooleanField(default=False)),
                ('allow_api_access', models.BooleanField(default=False)),
                ('allow_multiple_entreprises', models.BooleanField(default=False)),
                ('allow_advanced_analytics', models.BooleanField(default=False)),
                ('allow_custom_branding', models.BooleanField(default=False)),
                ('support_level', models.CharField(choices=[('email', 'Email'), ('priority', 'Prioritaire'), ('dedicated', 'Dédié')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('suspended', 'Suspendu')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Abonnement Entreprise',
                'verbose_name_plural': 'Abonnements Entreprise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.DateField(default=datetime.date(2025, 10, 1))),
                ('factures_count', models.IntegerField(default=0)),
                ('produits_count', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('boutiques_count', models.IntegerField(default=0)),
                ('total_factures', models.IntegerField(default=0)),
                ('total_produits', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_boutiques', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='core.entreprise')),
            ],
            options={
                'verbose_name': "Suivi d'utilisation",
                'verbose_name_plural': "Suivi d'utilisation",
                'ordering': ['-current_month'],
                'unique_together': {('entreprise', 'current_month')},
            },
        ),
    ]
