# Generated by Django 5.2 on 2025-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0028_subscriptionplan_entreprisesubscription_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['entreprise'], name='core_boutiq_entrepr_245391_idx'),
        ),
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['nom'], name='core_boutiq_nom_8acebd_idx'),
        ),
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['ville'], name='core_boutiq_ville_96d46d_idx'),
        ),
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['is_active'], name='core_boutiq_is_acti_d21fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='boutique',
            index=models.Index(fields=['entreprise', 'is_active'], name='core_boutiq_entrepr_cb4534_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['entreprise'], name='core_catego_entrepr_e84e66_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['nom'], name='core_catego_nom_8325b5_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['actif'], name='core_catego_actif_043643_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['entreprise', 'actif'], name='core_catego_entrepr_8a39a3_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['nom'], name='core_entrep_nom_50624c_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['email'], name='core_entrep_email_aec301_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['is_active'], name='core_entrep_is_acti_985a77_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['created_at'], name='core_entrep_created_e938d5_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['entreprise'], name='core_factur_entrepr_bdea56_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['boutique'], name='core_factur_boutiqu_f5623c_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['type'], name='core_factur_type_5a55dc_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['status'], name='core_factur_status_23487e_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['created_at'], name='core_factur_created_f8702b_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['boutique', 'created_at'], name='core_factur_boutiqu_381375_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['entreprise', 'created_at'], name='core_factur_entrepr_4e003f_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['entreprise'], name='core_fourni_entrepr_93c0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['nom'], name='core_fourni_nom_f47e38_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['code_fournisseur'], name='core_fourni_code_fo_f2c780_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['actif'], name='core_fourni_actif_d804b1_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['entreprise', 'actif'], name='core_fourni_entrepr_d33f28_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit'], name='core_mouvem_produit_c672dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['entrepot'], name='core_mouvem_entrepo_b8c8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='core_mouvem_type_mo_75d2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['utilisateur'], name='core_mouvem_utilisa_9636ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['created_at'], name='core_mouvem_created_fbdb66_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['entrepot', 'created_at'], name='core_mouvem_entrepo_1a4a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit', 'entrepot'], name='core_mouvem_produit_7d892c_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise'], name='core_produi_entrepr_357e62_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='core_produi_categor_99182b_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['fournisseur_principal'], name='core_produi_fournis_467621_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='core_produi_nom_87aef3_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['sku'], name='core_produi_sku_8bf18f_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['actif'], name='core_produi_actif_6c6e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise', 'actif'], name='core_produi_entrepr_5da979_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'actif'], name='core_produi_categor_f75788_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise', 'categorie'], name='core_produi_entrepr_7d9602_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['prix_vente'], name='core_produi_prix_ve_96668a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['created_at'], name='core_produi_created_2a78ba_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit'], name='core_stock_produit_e893df_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['entrepot'], name='core_stock_entrepo_9c071b_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantite'], name='core_stock_quantit_93d0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['entrepot', 'quantite'], name='core_stock_entrepo_4c41b4_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit', 'entrepot'], name='core_stock_produit_889208_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['updated_at'], name='core_stock_updated_00faa4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['entreprise'], name='core_user_entrepr_5468d9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['boutique'], name='core_user_boutiqu_1babf0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['entreprise', 'is_active'], name='core_user_entrepr_a85e31_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['boutique', 'is_active'], name='core_user_boutiqu_c1ff9e_idx'),
        ),
    ]
