# Generated by Django 5.1 on 2025-10-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires sous forme de JSON (clé-valeur)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='emplacement',
            field=models.CharField(blank=True, help_text="Emplacement physique du produit dans l'entrepôt", max_length=200, null=True),
        ),
    ]
