# Generated by Django 5.1 on 2025-10-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_inventaire_inventaireproduit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='date_ajustement',
            field=models.DateTimeField(blank=True, help_text="Date de l'ajustement des stocks", null=True),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='stocks_ajustes',
            field=models.BooleanField(default=False, help_text='Indique si les stocks ont été ajustés suite à cet inventaire'),
        ),
    ]
