# Generated by Django 5.1 on 2025-10-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_inventaire_stocks_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisesubscription',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Renouvellement automatique'),
        ),
        migrations.AddField(
            model_name='entreprisesubscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='alert_level',
            field=models.CharField(choices=[('none', 'Aucune'), ('simple', 'Simple - seuil par produit'), ('advanced', 'Avancé - multi-seuils + emails'), ('multi_warehouse', 'Multi-entrepôts')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_barcode_generation',
            field=models.BooleanField(default=False, help_text='Génération de codes-barres'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_inventory',
            field=models.BooleanField(default=False, help_text='Permet les inventaires'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_partners',
            field=models.BooleanField(default=False, help_text='Gestion des partenaires (clients/fournisseurs)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_transfers',
            field=models.BooleanField(default=False, help_text='Permet les transferts inter-entrepôts'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_inventaires_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_transfers_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
