# Generated by Django 4.2.26 on 2025-11-07 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_subscription_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencefacture',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences_facture', to='core.boutique'),
        ),
        migrations.AlterField(
            model_name='usagetracking',
            name='current_month',
            field=models.DateField(default=datetime.date(2025, 11, 1)),
        ),
    ]
