# Generated by Django 4.2.26 on 2026-06-19 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fix_sequence_facture_unique_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partenaire',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='core.entreprise'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='pack_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('organisation', 'Organisation')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='core.boutique'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usagetracking',
            name='current_month',
            field=models.DateField(default=datetime.date(2026, 6, 1)),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['boutique'], name='core_parten_boutiqu_bf8f69_idx'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['entreprise'], name='core_parten_entrepr_046b54_idx'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['statut'], name='core_parten_statut_83eaef_idx'),
        ),
    ]
