# Generated by Django 4.2.26 on 2026-06-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_partenaire_boutique_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=5)),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('stripe', 'Carte bancaire (Stripe)'), ('bank_card', 'Carte bancaire'), ('manual', 'Manuel (admin)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10)),
                ('external_reference', models.CharField(blank=True, help_text='Référence chez le prestataire de paiement', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Pour OM/MTN', max_length=20)),
                ('card_last4', models.CharField(blank=True, help_text='4 derniers chiffres carte', max_length=4)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.entreprise')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_initiated', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.entreprisesubscription')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entreprise'], name='core_paymen_entrepr_37e267_idx'), models.Index(fields=['status'], name='core_paymen_status_04c981_idx'), models.Index(fields=['method'], name='core_paymen_method_a86f58_idx'), models.Index(fields=['created_at'], name='core_paymen_created_379b26_idx')],
            },
        ),
    ]
