# Generated by Django 4.2.26 on 2026-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_boutiques',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
