# Generated by Django 4.2.26 on 2026-06-24 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_subscription_plan_nullable_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text="Année de l'exercice (ex: 2024)")),
                ('date_debut', models.DateField(help_text="Date de début de l'exercice")),
                ('date_fin', models.DateField(help_text="Date de fin de l'exercice")),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='ouvert', max_length=20)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nb_factures', models.IntegerField(default=0)),
                ('valeur_stock_cloture', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nb_produits', models.IntegerField(default=0)),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_clotures', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_fiscaux', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Exercice fiscal',
                'verbose_name_plural': 'Exercices fiscaux',
                'ordering': ['-annee'],
                'indexes': [models.Index(fields=['entreprise', 'annee'], name='core_exerci_entrepr_3068e4_idx'), models.Index(fields=['statut'], name='core_exerci_statut_042f05_idx')],
                'unique_together': {('entreprise', 'annee')},
            },
        ),
    ]
