# Generated by Django 4.2.26 on 2026-06-26 14:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_exercice_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='limite_credit',
            field=models.FloatField(default=0, help_text='Plafond de crédit autorisé (0 = illimité)'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes internes sur le partenaire'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='entreprises/logos/', validators=[core.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit', null=True, upload_to='produits/images/', validators=[core.models.validate_image_file]),
        ),
    ]
