# Generated by Django 4.2.26 on 2026-06-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_partenaire_limite_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la variante (ex: 500ml, Rouge - L)', max_length=200)),
                ('attributs', models.JSONField(blank=True, default=dict, help_text='Attributs libres ex: {"Grammage":"500g","Couleur":"Rouge"}')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante produit',
                'verbose_name_plural': 'Variantes produit',
                'ordering': ['produit', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='produitvariante',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='core.produit'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='core.produitvariante'),
        ),
        migrations.AddField(
            model_name='commandepartenaire',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_partenaire', to='core.produitvariante'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante concernée (null = produit sans variante)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.produitvariante'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('variante__isnull', True)), fields=('produit', 'entrepot'), name='unique_stock_produit_entrepot'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('variante__isnull', False)), fields=('variante', 'entrepot'), name='unique_stock_variante_entrepot'),
        ),
        migrations.AddIndex(
            model_name='produitvariante',
            index=models.Index(fields=['produit'], name='core_produi_produit_0d75c5_idx'),
        ),
        migrations.AddIndex(
            model_name='produitvariante',
            index=models.Index(fields=['actif'], name='core_produi_actif_e3c6c9_idx'),
        ),
    ]
