# Generated by Django 4.2.26 on 2026-06-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_produitvariante_alter_stock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante concernée (null = produit sans variante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='core.produitvariante'),
        ),
    ]
