# Generated by Django 4.2.26 on 2026-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_variante_to_mouvementstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='pack_type',
            field=models.CharField(choices=[('free', 'Essai Gratuit'), ('starter', 'Starter'), ('business', 'Business'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Essai Gratuit'), ('starter', 'Starter'), ('business', 'Business'), ('pro', 'Pro')], max_length=20, unique=True),
        ),
    ]
